# Generated by Django 3.0.8 on 2020-09-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParliamentMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('political_force', models.CharField(blank=True, max_length=100, null=True)),
                ('language1', models.CharField(blank=True, max_length=100, null=True)),
                ('language2', models.CharField(blank=True, max_length=100, null=True)),
                ('language3', models.CharField(blank=True, max_length=100, null=True)),
                ('language4', models.CharField(blank=True, max_length=100, null=True)),
                ('language5', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('profession1', models.CharField(blank=True, max_length=100, null=True)),
                ('profession2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
